# Generated by Django 3.1.2 on 2020-12-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoRestTut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.CharField(default='tawanda', max_length=240),
            preserve_default=False,
        ),
    ]
